name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 设置 Node.js 环境
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: 安装 pnpm
      run: npm install -g pnpm
      
    - name: 安装依赖
      run: pnpm install
      
    - name: 构建项目
      run: pnpm run build
